/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  bonsai: [
    "intro",
    {
      label: "Product Feeds",
      type: "category",
      link: {
        type: "generated-index",
        description: "We currently provide access to our product catalogue via product feeds. This section includes implementation steps and best practices to start using our feeds."
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'product-feeds',
        },
      ]
    },
    {
      type: "category",
      label: "Bonsai API",
      link: {
        type: "doc",
        id: "api/index",
      },
      items: [
        {
          type: "category",
          label: "Products",
          link: {
            type: "doc",
            id: "api/products/products-api",
          },
          items: [
            {
              type: "doc",
              id: "api/products/get-products",
              label: "Get Products",
              className: "api-method get",
            },
          ],
        },
        {
          type: "category",
          label: "Orders",
          link: {
            type: "doc",
            id: "api/orders/orders-api",
          },
          items: [
            {
              type: "category",
              label: "Checkout Totals",
              className: "api-method post",
              link: {
                type: "doc",
                id: "api/orders/checkout-totals"
              },
              items: [
                {
                  type: "doc",
                  id: "api/orders/checkout-error-responses",
                },
              ],
            },
            {
              type: "category",
              label: "Submit Orders",
              className: "api-method post",
              link: {
                type: "doc",
                id: "api/orders/submit-orders"
              },
              items: [
                {
                  type: "doc",
                  id: "api/orders/orders-error-responses",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: "doc",
      id: "images/index",
      label: "Images",
    },
    {
      type: "doc",
      id: "express-checkout/index",
      label: "Express Checkout",
    },
    {
      type: "doc",
      id: "native-commerce/index",
      label: "Native Commerce",
    },
    {
      type: "doc",
      id: "inventory-validation/index",
      label: "Inventory Validation",
    },
  ],
};

module.exports = sidebars;
