/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  bonsai: [
    'intro',
    {
      label: 'Product Feeds',
      type: 'category',
      link: {
        type: 'generated-index',
        description:
          'We currently provide access to our product catalogue via product feeds. This section includes implementation steps and best practices to start using our feeds.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'product-feeds',
        },
      ],
    },
      label: "Bonsai UI",
      type: "category",
      link: {
        type: "doc",
        type: 'doc',
        id: 'api/index',
        id: "bonsai-ui/introduction",
      },
      items: [
          type: 'category',
          label: 'Products',
          id: "bonsai-ui/express-checkout/index",
            type: 'doc',
            id: 'api/products/products-api',
        {
          type: "doc",
          id: "bonsai-ui/checkout/index",
              type: 'doc',
              id: 'api/products/get-products',
              label: 'Get Products',
              className: 'api-method get',
  ],
};

module.exports = sidebars;
